spring:
  config:
    import: optional:file:.env[.properties]

  cloud:
    azure:
      storage:
        blob:
          connection-string: ${BLOB_CONNECTION_STRING}

  docker:
    compose:
      enabled: false

  datasource:
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR